const spacing = {
  'xs': '32rem',
  'sm': '48rem',
  'md': '64rem',
  'lg': '80rem',
  'xl': '96rem',
  '2xl': '112rem',
  '3xl': '128rem',
  '4xl': '144rem',
  '5xl': '160rem',
  'auto': 'auto',
  'px': '1px',
  '0': '0',
  '1': '0.25rem',
  '2': '0.5rem',
  '3': '0.75rem',
  '4': '0.4rem',
  '5': '0.5rem',
  '6': '0.6rem',
  '8': '0.8rem',
  '10': '1rem',
  '12': '1.2rem',
  '16': '1.6rem',
  '18': '1.8rem',
  '20': '2rem',
  '24': '2.4rem',
  '28': '2.8rem',
  '32': '3.2rem',
  '36': '3.6rem',
  '40': '4rem',
  '44': '4.4rem',
  '48': '4.8rem',
  '52': '5.2rem',
  '56': '5.6rem',
  '60': '6rem',
  '64': '6.4rem',
  '68': '6.8rem',
  '72': '7.2rem',
  '76': '7.6rem',
  '80': '8rem',
  '84': '8.4rem',
  '88': '8.8rem',
  '92': '9.2rem',
  '96': '9.6rem',
  '128': '12.8rem',
  '136': '13.6rem',
  '160': '16rem',
  '176': '17.6rem',
  '192': '19.2rem',
  '200': '20rem',
  '208': '20.8rem',
  '216': '21.6rem',
  '224': '22.4rem',
  '256': '25.6rem',
  '288': '28.8rem',
  '295': '29.5rem',
  '320': '32rem',
  '360': '36rem',
  '384': '38.4rem',
  '400': '40rem',
  '452': '45.2rem',
  '480': '48rem',
  '512': '51.2rem',
  '582': '58.2rem',
  '640': '64rem',
  'content': 'fit-content',
};

const indentSpacing = {
  'px': '1px',
  '0': '0',
  '1': '0.25rem',
  '2': '0.5rem',
  '3': '0.75rem',
  '4': '0.4rem',
  '5': '0.5rem',
  '6': '0.6rem',
  '8': '0.8rem',
  '10': '1rem',
  '12': '1.2rem',
  '16': '1.6rem',
  '18': '1.8rem',
  '20': '2rem',
  '24': '2.4rem',
  '28': '2.8rem',
  '32': '3.2rem',
  '36': '3.6rem',
  '40': '4rem',
  '44': '4.4rem',
  '48': '4.8rem',
  '52': '5.2rem',
  '56': '5.6rem',
  '60': '6rem',
  '64': '6.4rem',
  '68': '6.8rem',
  '72': '7.2rem',
  '76': '7.6rem',
  '80': '8rem',
  '84': '8.4rem',
  '88': '8.8rem',
  '92': '9.2rem',
  '96': '9.6rem',
};

const width = {
  auto: 'auto',
  full: '100%',
  screen: '100vw',
  '1/2': '50%',
  '1/3': '33.33333%',
  '2/3': '66.66667%',
  '1/4': '25%',
  '2/4': '50%',
  '3/4': '75%',
  '1/5': '20%',
  '2/5': '40%',
  '3/5': '60%',
  '4/5': '80%',
  '1/6': '16.66667%',
  '2/6': '33.33333%',
  '3/6': '50%',
  '4/6': '66.66667%',
  '5/6': '83.33333%',
  '2/9': '22.22222%',
  '4/9': '44.44444%',
  '1/12': '8.33333%',
  '2/12': '16.66667%',
  '3/12': '25%',
  '4/12': '33.33333%',
  '5/12': '41.66667%',
  '6/12': '50%',
  '7/12': '58.33333%',
  '8/12': '66.66667%',
  '9/12': '75%',
  '10/12': '83.33333%',
  '11/12': '91.66667%',
};

module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  prefix: '',
  important: 'body',
  separator: ':',
  theme: {
    extend: {
      animation: {
        'spin-slow': 'spin 3s linear infinite',
        'ping-slow': 'ping 2s cubic-bezier(0, 0, 0.2, 1) infinite',
      },
      spacing: spacing,
      colors: {
        'background-page': '#F5F5F5',
        'background-table': '#FFFFFF',
        'button': '#4CAF50',
        'button-border': '#4CAF50',
        'button-text': '#FFFFFF',
        'button-hover': '#3E8E41',
        'table-separator': '#E0E0E0',
        'table-header': '#2196F3',
        'page-header': '#2196F3',
        'footer': '#E0E0E0',
        'heading-font': '#212121',
        'body-font': '#757575',
      },
      backgroundColor: ({ theme }) => ({
        ...theme('colors'),
      }),
      textColor: ({ theme }) => ({
        ...theme('colors'),
      }),
      screens: {
        sm: '600px',
        md: '960px',
        lg: '1280px',
        xl: '1920px',
        print: { 'raw': 'print' },
      },
      fontFamily: {
        sans: [
          'Roboto',
          'Muli',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Oxygen',
          'Ubuntu',
          'Cantarell',
          'Fira Sans',
          'Droid Sans',
          'Helvetica Neue',
          'sans-serif',
        ],
        serif: [
          'Roboto',
          'Constantia',
          'Lucida Bright',
          'Lucidabright',
          'Lucida Serif',
          'Lucida',
          'DejaVu Serif',
          'Bitstream Vera Serif',
          'Liberation Serif',
          'Georgia',
          'serif',
        ],
        mono: [
          'Roboto',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      fontSize: {
        xs: '1.2rem',     // 12px
        sm: '2.4rem',     // 24px
        base: '1.6rem',     // 16px
        lg: '1.8rem',     // 18px
        xl: '2rem',       // 20px
        '2xl': '2.4rem',     // 24px
        '3xl': '3rem',       // 30px
        '4xl': '3.6rem',     // 36px
        '5xl': '4.8rem',      // 48px,
        '10': '1rem',
        '11': '1.1rem',
        '12': '1.2rem',
        '13': '1.3rem',
        '14': '1.4rem',
        '15': '1.5rem',
        '16': '1.6rem',
        '17': '1.7rem',
        '18': '1.8rem',
        '19': '1.9rem',
        '20': '2rem',
        '22': '2.2rem',
        '24': '2.4rem',
        '28': '2.8rem',
        '32': '3.2rem',
        '36': '3.6rem',
        '40': '4rem',
        '44': '4.4rem',
        '48': '4.8rem',
        '52': '5.2rem',
        '56': '5.6rem',
        '60': '6rem',
        '64': '6.4rem',
        '68': '6.8rem',
        '72': '7.2rem',
        '96': '9.6rem',
        '128': '12.8rem',
      },
      fontWeight: {
        hairline: '100',
        thin: '200',
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
        '100': '100',
        '200': '200',
        '300': '300',
        '400': '400',
        '500': '500',
        '600': '600',
        '700': '700',
        '800': '800',
        '900': '900',
      },
      lineHeight: {
        none: '1',
        tight: '1.25',
        snug: '1.375',
        normal: '1.5',
        relaxed: '1.625',
        loose: '2',
      },
      letterSpacing: {
        tighter: '-0.05em',
        tight: '-0.025em',
        normal: '0',
        wide: '0.025em',
        wider: '0.05em',
        widest: '0.1em',
      },
      backgroundPosition: {
        bottom: 'bottom',
        center: 'center',
        left: 'left',
        'left-bottom': 'left bottom',
        'left-top': 'left top',
        right: 'right',
        'right-bottom': 'right bottom',
        'right-top': 'right top',
        top: 'top',
      },
      backgroundSize: {
        auto: 'auto',
        cover: 'cover',
        contain: 'contain',
      },
      borderWidth: {
        default: '1px',
        '0': '0',
        '1': '1px',
        '2': '2px',
        '3': '3px',
        '4': '4px',
        '8': '8px',
      },
      borderColor: ({ theme }) => ({
        ...theme('textColor'),
        default: theme('colors.gray.300', 'currentColor'),
      }),
      borderRadius: {
        none: '0',
        sm: '.2rem',
        default: '.4rem',
        lg: '.8rem',
        full: '9999px',
        '2': '.2rem',
        '4': '.4rem',
        '6': '.6rem',
        '8': '.8rem',
        '12': '1.2rem',
        '16': '1.6rem',
        '20': '2rem',
        '24': '2.4rem',
        '28': '2.8rem',
        '32': '3.2rem',
      },
      cursor: {
        auto: 'auto',
        default: 'default',
        pointer: 'pointer',
        wait: 'wait',
        text: 'text',
        move: 'move',
        'not-allowed': 'not-allowed',
      },
      width: ({ theme }) => ({
        ...width,
        ...theme('spacing'),
      }),
      height: ({ theme }) => ({
        auto: 'auto',
        full: '100%',
        screen: '100vh',
        ...theme('spacing'),
      }),
      minWidth: ({ theme }) => ({
        ...width,
        ...theme('spacing'),
      }),
      minHeight: ({ theme }) => ({
        'auto': 'auto',
        full: '100%',
        screen: '100vh',
        ...theme('spacing'),
      }),
      maxWidth: ({ theme }) => ({
        ...width,
        ...theme('spacing'),
      }),
      maxHeight: ({ theme }) => ({
        'auto': 'auto',
        full: '100%',
        screen: '100vh',
        ...theme('spacing'),
      }),
      padding: ({ theme }) => theme('spacing'),
      objectPosition: {
        bottom: 'bottom',
        center: 'center',
        left: 'left',
        'left-bottom': 'left bottom',
        'left-top': 'left top',
        right: 'right',
        'right-bottom': 'right bottom',
        'right-top': 'right top',
        top: 'top',
      },
      zIndex: {
        auto: 'auto',
        '0': '0',
        '10': '10',
        '20': '20',
        '30': '30',
        '40': '40',
        '50': '50',
        '99': '99',
        '999': '999',
        '9999': '9999',
      },
      opacity: {
        '0': '0',
        '25': '0.25',
        '50': '0.5',
        '75': '0.75',
        '100': '1',
      },
      fill: {
        current: 'currentColor',
      },
      stroke: {
        current: 'currentColor',
      },
      flex: {
        '1': '1 1 0%',
        auto: '1 1 auto',
        initial: '0 1 auto',
        none: 'none',
      },
      flexGrow: {
        '0': '0',
        default: '1',
      },
      flexShrink: {
        '0': '0',
        default: '1',
      },
      order: {
        first: '-9999',
        last: '9999',
        none: '0',
        '1': '1',
        '2': '2',
        '3': '3',
        '4': '4',
        '5': '5',
        '6': '6',
        '7': '7',
        '8': '8',
        '9': '9',
        '10': '10',
        '11': '11',
        '12': '12',
      },
      listStyleType: {
        none: 'none',
        disc: 'disc',
        decimal: 'decimal',
      },
      inset: {
        '0': '0',
        auto: 'auto',
      },
      container: {},
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [],
  safelist: [
    {
      pattern: /text-[a-z\-0-9]+/,
      variants: ['hover'],
    },
    {
      pattern: /text-[0-9]+/,
      variants: ['sm', 'md', 'lg'],
    },
    {
      pattern: /border-[a-z\-0-9]+/,
      variants: ['hover'],
    },
    {
      pattern: /bg-[a-z\-0-9]+/,
      variants: ['hover'],
    },
    ...Object.keys(width).map(widthClassKey => `w-${widthClassKey}`),
    ...Object.keys(spacing).map(spacingClassKey => `w-${spacingClassKey}`),
    'h-auto',
    'h-full',
    'h-screen',
    ...Object.keys(spacing).map(spacingClassKey => `h-${spacingClassKey}`),
    ...Object.keys(width).map(widthClassKey => `min-w-${widthClassKey}`),
    ...Object.keys(spacing).map(spacingClassKey => `min-w-${spacingClassKey}`),
    'min-h-auto',
    'min-h-full',
    'min-h-screen',
    ...Object.keys(spacing).map(spacingClassKey => `min-h-${spacingClassKey}`),
    ...Object.keys(spacing).map(spacingClassKey => `max-w-${spacingClassKey}`),
    ...Object.keys(width).map(widthClassKey => `max-w-${widthClassKey}`),
    'max-h-auto',
    'max-h-full',
    'max-h-screen',
    ...Object.keys(spacing).map(spacingClassKey => `max-h-${spacingClassKey}`),
    ...Object.keys(indentSpacing).map(spacingClassKey => `p-${spacingClassKey}`),
    ...Object.keys(indentSpacing).map(spacingClassKey => `px-${spacingClassKey}`),
    ...Object.keys(indentSpacing).map(spacingClassKey => `py-${spacingClassKey}`),
    ...Object.keys(indentSpacing).map(spacingClassKey => `pt-${spacingClassKey}`),
    ...Object.keys(indentSpacing).map(spacingClassKey => `pr-${spacingClassKey}`),
    ...Object.keys(indentSpacing).map(spacingClassKey => `pb-${spacingClassKey}`),
    ...Object.keys(indentSpacing).map(spacingClassKey => `pl-${spacingClassKey}`),
    ...Object.keys(indentSpacing).map(spacingClassKey => `m-${spacingClassKey}`),
    ...Object.keys(indentSpacing).map(spacingClassKey => `mx-${spacingClassKey}`),
    ...Object.keys(indentSpacing).map(spacingClassKey => `my-${spacingClassKey}`),
    ...Object.keys(indentSpacing).map(spacingClassKey => `mt-${spacingClassKey}`),
    ...Object.keys(indentSpacing).map(spacingClassKey => `mr-${spacingClassKey}`),
    ...Object.keys(indentSpacing).map(spacingClassKey => `ml-${spacingClassKey}`),
  ],
};
