ALTER TABLE category
ALTER COLUMN name TYPE TEXT;

ALTER TABLE team
ALTER COLUMN name TYPE TEXT;

ALTER TABLE author
ALTER COLUMN name TYPE TEXT;

ALTER TABLE practice
ALTER COLUMN name TYPE TEXT;

ALTER TABLE practice
ALTER COLUMN description TYPE TEXT;

ALTER TABLE practice
ALTER COLUMN document_link TYPE TEXT;