POST http://localhost:8080/practices
content-type: application/json

{
  "name": "Еще одна практика",
  "description": "Описание еще одной практики",
  "documentLink": "https://lala",
  "rating": 0,
  "team":  "Hello нейроWorld",
  "category": "Разработка",
  "author":  "Кодер"
}

###
POST http://localhost:8080/practices/search

###
GET http://localhost:8080/practices/3